export const EXERCISE_SCHEMAS = {
  FILL_BLANK: {
    title: "string - titolo descrittivo",
    instructions: "string",
    text: "string con ___GAP_1___ ___GAP_2___ placeholder",
    gaps: [{ id: "GAP_1", answer: "string", alternatives: ["string"], hint: "string opzionale" }],
    wordBank: ["tutte le parole corrette + eventuali distrattori, mescolate in ordine casuale"],
  },
  MULTIPLE_CHOICE: {
    title: "string",
    instructions: "string",
    questions: [{
      id: "Q1", text: "string",
      options: [{ id: "a", text: "string" }, { id: "b", text: "string" }, { id: "c", text: "string" }, { id: "d", text: "string" }],
      correctOptionId: "a", explanation: "string opzionale",
    }],
  },
  MATCHING: {
    title: "string",
    instructions: "string",
    pairs: [{ id: "P1", left: "string parola/frase", right: "string definizione/traduzione" }],
  },
  REORDER: {
    title: "string",
    instructions: "string",
    sentences: [{ id: "S1", words: ["array", "di", "parole", "disordinate"], correctOrder: [0, 1, 2, 3], hint: "string opzionale" }],
  },
  CLOZE: {
    title: "string",
    instructions: "string",
    passage: "testo con ___1___ ___2___ placeholder numerati",
    gaps: [{ id: "1", answer: "string", position: 1 }],
    wordBank: ["parola1", "parola2", "opzionale"],
  },
  TRUE_FALSE: {
    title: "string",
    instructions: "string",
    text: "testo di riferimento opzionale",
    statements: [{ id: "S1", statement: "string", answer: "true|false|not_given", justification: "string" }],
  },
  SHORT_ANSWER: {
    title: "string",
    instructions: "string",
    questions: [{ id: "Q1", question: "string", sampleAnswer: "string", keywords: ["parola1", "parola2"], maxWords: 50 }],
  },
  ESSAY: {
    title: "string",
    instructions: "string",
    prompt: "string - traccia del tema",
    minWords: 150,
    maxWords: 250,
    rubric: { content: "criteri contenuto", grammar: "criteri grammatica", vocabulary: "criteri vocabolario", structure: "criteri struttura" },
  },
  READING_COMP: {
    title: "string",
    instructions: "string",
    passage: "testo lungo da leggere",
    questions: [{ id: "Q1", question: "string", type: "multiple_choice|short_answer|true_false", options: [{ id: "a", text: "string" }], correctAnswer: "string" }],
  },
  LISTENING_COMP: {
    title: "string",
    instructions: "string",
    transcript: "trascrizione del testo audio simulato",
    questions: [{ id: "Q1", question: "string", type: "multiple_choice|short_answer", options: [{ id: "a", text: "string" }], correctAnswer: "string" }],
  },
  DIALOGUE_COMPLETE: {
    title: "string",
    instructions: "string",
    scenario: "string - contesto della conversazione",
    dialogue: [{ id: "D1", speaker: "string", text: "string visibile o ___ se gap", isGap: false, answer: "string se isGap=true", options: ["opzione1"] }],
  },
  ERROR_CORRECTION: {
    title: "string",
    instructions: "string",
    sentences: [{ id: "S1", incorrect: "frase con errore", correct: "frase corretta", errorType: "tipo errore es. verb tense" }],
  },
  WORD_FORMATION: {
    title: "string",
    instructions: "string",
    context: "string opzionale",
    items: [{ id: "I1", sentence: "frase con ___", baseWord: "parola base tra parentesi", answer: "forma corretta" }],
  },
  TRANSLATION: {
    title: "string",
    instructions: "string",
    direction: "it_to_en|en_to_it",
    items: [{ id: "T1", source: "testo da tradurre", target: "traduzione corretta", notes: "note opzionali" }],
  },
  DICTATION: {
    title: "string",
    instructions: "string",
    text: "testo completo da dettare",
    hint: "string opzionale",
    focusPoints: ["aspetto1", "aspetto2"],
  },
  CONVERSATION_SIM: {
    title: "string",
    instructions: "string",
    scenario: "string - contesto",
    role: "string - ruolo AI/insegnante",
    studentRole: "string - ruolo studente",
    targetVocabulary: ["parola1", "parola2"],
    targetGrammar: "struttura grammaticale target",
    turnsExpected: 6,
    starterLine: "battuta iniziale per cominciare",
  },
}
